declare namespace Telegram {
    interface Update {
        update_id: number,
        message?: Telegram.Message,
        edited_message?: Telegram.Message,
        channel_post?: Telegram.Message,
        edited_channel_post?: Telegram.Message,
        message_reaction?: Telegram.MessageReactionUpdated,
        message_reaction_count?: Telegram.MessageReactionCountUpdated,
        inline_query?: Telegram.InlineQuery,
        chosen_inline_result?: Telegram.ChosenInlineResult,
        callback_query?: Telegram.CallbackQuery,
        poll?: Telegram.Poll,
        poll_answer?: Telegram.PollAnswer,
        my_chat_member?: Telegram.ChatMemberUpdated,
        chat_member?: Telegram.ChatMemberUpdated,
        chat_join_request?: Telegram.ChatJoinRequest,
        chat_boost?: Telegram.ChatBoostUpdated,
        removed_chat_boost?: Telegram.ChatBoostRemoved,
    }

    interface Message {
        message_id: number,
        message_thread_id?: number,
        from?: Telegram.User,
        sender_chat: Telegram.Chat,
        sender_boost_count?: number,
        date: number,
        chat: Telegram.Chat,
        forward_origin?: Telegram.MessageOrigin,
        is_topic_message?: boolean,
        is_automatic_forward?: boolean,
        reply_to_message?: Telegram.Message,
        external_reply?: Telegram.ExternalReplyInfo,
        quote?: Telegram.TextQuot,
        reply_to_story?: Telegram.Story,
        via_bot?: Telegram.User,
        edit_date?: number,
        has_protected_content?: boolean,
        is_from_offline?: boolean,
        media_group_id?: string,
        author_signature?: string,
        text?: string,
        entities?: Telegram.MessageEntity[],
        link_preview_options?: Telegram.LinkPreviewOptions,
        effect_id?: string,
        animation?: Telegram.Animation,
        audio?: Telegram.Audio,
        document?: Telegram.Document,
        paid_media?: Telegram.PaidMediaInfo,
        photo?: Telegram.PhotoSize[],
        sticker?: Telegram.Sticker,
        story?: Telegram.Story,
        video?: Telegram.Video,
        video_note?: Telegram.VideoNote,
        voice?: Telegram.Voice,
        caption?: string,
        caption_entities?: Telegram.MessageEntity,
        show_caption_above_media?: boolean,
        has_media_spoiler?: boolean,
        contact?: Telegram.Contact,
        dice?: Telegram.Dice,
        game?: Telegram.Game,
        poll?: Telegram.Poll,
        venue?: Telegram.Venue,
        location?: Telegram.Location,

    }
}
